Feat: Implementation of NuBank statement parser
viceespi/popoupa pull request #2
Opened 2023-09-30 22:09 UTC by viceespi

2023-09-30 22:11 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +        public List<string> GetLines(string filestring)
Why does this method need to be public, if it's only used within the class?

2023-09-30 22:11 UTC, viceespi commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +        public List<string> GetLines(string filestring)
me dumb

2023-09-30 22:29 UTC, thfsilvab requested changes

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core.UnitTests/NubankCSVParserTests.cs
> +    public class NubankCSVParserTests
It doesn't seem like all the test cases are covered in this test class, please test all scenarios.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            foreach (string line in csvLines)
If you're tracking the line with indexes, wouldn't it be better to use a `for` loop statement instead?
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +                if (line != csvLines[0])
This condition seems to be easily removed if you use the `for` loop statement, just start the variable with `var i = 1` instead of `0`. But this will only work if the first line is actually a header, which I'd like some validations on if possible, because if the scenario where the header gets removed shows up, we'll be missing one record by jumping one line and not track the error. A method like `private bool IsHeaderLine(string line)` should suffice.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +                    var isExpense = GetExpenseAmount(separatedLine, index, out expenseAmount);
This can be changed to `var isExpense = GetExpenseAmount(separatedLine, index, out decimal expenseAmount);`, then you can remove `Decimal expenseAmount;` entirely.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +        public List<string> GetLines(string filestring)
Consider using the `string.Split()` method instead of implementing it on your own: https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=net-7.0

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +        public List<string> GetColumns(string line)
Same thing here, consider using the `string.Split()`: https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=net-7.0

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            CultureInfo brazilian = new CultureInfo("pt-BR");
If the same culture is used every time this method is called, then this is not a variable but a constant instead. You can avoid unnecessary allocations by making it a `private static readonly CultureInfo BrazilianCultureInfo = new CultureInfo("pt-BR");` at the class level, and use it in the method.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            var dateAsString = lineContents[0];
This can throw an exception if the line is empty, please consider having it handled.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +        public DateTime GetExpenseDate(List<string> lineContents, int lineIndex)
This method can be marked as `private` if it's only used internally, I also see the possibility of making it `static` and marking it as `[Pure]` because it's not changing the parameters nor doing any IO.

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute?view=net-7.0

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +        public bool GetExpenseAmount(List<string> lineContents, int lineIdex, out decimal Amount)
Consider making this method `private` as well, since it's only used within this class

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            if (amountAsString[0] == '-')
`amountAsString[0]` may throw an exception if the index is out of bounds (aka empty array), consider catching the exception.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            var amountAsString = lineContents[1];
`lineContents[1]` may throw an exception if the index is out of bounds, consider catching the exception.

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +                    return true;
I see what you tried to do here, but there's a method for this `decimal.TryParse()`, you're code's going to look cleaner and easier to read.

https://learn.microsoft.com/en-us/dotnet/api/system.decimal.tryparse?view=net-7.0

2023-09-30 22:29 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            var expenseDescription = lineContents[3];
`lineContents[3]` may throw an exception when the index is out of bounds, consider treating the error.

2023-10-03 10:42 UTC, thfsilvab requested changes

2023-10-03 10:42 UTC, thfsilvab commented on src/backend/Popoupa.Core/InvalidBankStatementException.cs
> +        public InvalidBankStatementException(int CsvLineReference, string message) : base(message)
The parameter `CsvLineReference` first character has to be lower-case to follow the camel-case convention.

2023-10-03 10:42 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +                var CsvLineReference = lineIndex + 1;
The variable name must start with a lower-case character, following the camel-case convention.

2023-10-03 10:42 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            var hasHeader = HasHeader(fileString);
If the `HasHeader` method already throws an exception if there's no header, there's no meaning returning a boolean that will only have a `true` value and nothing will be done with it.

2023-10-03 10:42 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +                CheckIfLineIsValid(lineContents, CsvLineReference);
While there's nothing wrong in calling a method without a return, the intention is what I'm worried about here. You're in the `Parse` method and you're transferring the flow control to another method by throwing an exception in that method in case a condition is not met. There's also nothing wrong with it, but it increases complexity when you're analyzing the code, and can lead to longer debugging sessions to find a bug and harder to comprehend code as well.

2023-10-03 10:42 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            var header = "Data,Valor,Identificador,Descrição\r\n";
This can be a `const string` instead of a `var`.

2023-10-03 10:42 UTC, thfsilvab commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +            CultureInfo brazilian = new CultureInfo("pt-BR");
This culture info can be `private static readonly CultureInfo` at the class level instead of a variable at the method level.

2023-10-03 17:46 UTC, viceespi commented on src/backend/Popoupa.Core/NubankCSVParser.cs
> +                CheckIfLineIsValid(lineContents, CsvLineReference);
It seems that we disagree in regards of the ownership of the flow control. Since i am the one responsible for the design of the code, and there's nothing wrong whit calling a method without a return, i would like to maintain my code design, in which each exception goes out of the main method, as i think that less scopes in a method makes for a more fluid code to review.

2024-01-05 16:37 UTC, thfsilvab approved these changes

2024-01-05 16:37 UTC, merged